language: node_js

node_js:
  - "stable"
script: npm run $COMMAND

env:
  matrix:
  - COMMAND=test
  - COMMAND=test-phantom
  - COMMAND=report-coverage

branches:
  only:
  - master
  - /^greenkeeper-.*$/
